INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'CGS 2518', N'Computer Data Analysis')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'CGS 4854', N'Website Construction and Management')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'CNT 4403', N'Computer and Network Security')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'COP 2210', N'Programming 1')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'COP 3337', N'Programming 2')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'COP 3530 ', N'Data Structures')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'COP 4005', N'Windows Programming for IT')
INSERT [dbo].[COURSE] ([CourseID], [CourseName]) VALUES (N'CTS 4408 ', N'Database Administration')
INSERT [dbo].[EVENT_TYPE] ([EventTypeID], [EventTypeDescription]) VALUES (N'eBoard Mtg', N'Executive Board Meeting')
INSERT [dbo].[EVENT_TYPE] ([EventTypeID], [EventTypeDescription]) VALUES (N'Gen Mtg', N'General Meeting')
INSERT [dbo].[EVENT_TYPE] ([EventTypeID], [EventTypeDescription]) VALUES (N'Outreach ', N'Outreach Event')
INSERT [dbo].[EVENT_TYPE] ([EventTypeID], [EventTypeDescription]) VALUES (N'RISE Mtg', N'Rise Project Meeting')
INSERT [dbo].[EVENT_TYPE] ([EventTypeID], [EventTypeDescription]) VALUES (N'Special', N'Special presentation')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Admin', N'Administrator')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Guest', N'Guest')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Member', N'Regular member')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Officer', N'STARS Officer')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Tutor - Paid', N'Paid tutor position')
INSERT [dbo].[ROLE] ([RoleID], [RoleDescription]) VALUES (N'Tutor - Vol', N'Volunteer tutor position')
INSERT [dbo].[SEMESTER] ([SemesterID], [SemesterDescription]) VALUES (N'fa16', N'Fall 2016')
INSERT [dbo].[SEMESTER] ([SemesterID], [SemesterDescription]) VALUES (N'fa17', N'Fall 2017')
INSERT [dbo].[SEMESTER] ([SemesterID], [SemesterDescription]) VALUES (N'sp17', N'Spring 2017')
INSERT [dbo].[SEMESTER] ([SemesterID], [SemesterDescription]) VALUES (N'su17', N'Summer 2017')
